export const PINTER_PRODUCTS = [
  {
    id: 'guinness-dublin-porter',
    name: "Guinness 'Dublin Porter'",
    style: 'Stout',
    abv: 3.8,
    brewingDays: 6,
    conditioningDays: 4,
    description: 'Guinness Dublin Porter, Brewers Edition is inspired by the original brewing books of Arthur Guinness. A sweet, smooth beer, deep and rich, with a hint of ruby red. With a smooth mouthfeel and a hint of caramel mixed with elegant hops, and the same roasted Irish barley you know and love.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/GuinnessDublinPorterBundle2Artboard_1_large_crop_center@2x.jpg?v=1743079906',
    
  },
  {
    id: 'brewdog-elvis-juice-remixed',
    name: 'BrewDog Elvis Juice Remixed',
    style: 'Grapefruit IPA',
    abv: 6.5,
    brewingDays: 9,
    conditioningDays: 5,
    description: 'PINTER GOES FULL FRONTAL CITRUS. A citrus lover\'s dream, combining the bright, zesty flavours of freshly picked oranges and grapefruits with the bold, hop-forward character of an IPA. This beer pours a golden pale colour, with invigorating aromas of juicy citrus, floral hops, and a hint of tropical fruit. On the palate, it\'s a burst of vibrant citrus flavours, with sweet orange and tangy grapefruit taking centre stage, balanced by a crisp hop bitterness.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/BrewDog-ElvisJuiceRemixed_03copy_large_crop_center@2x.jpg?v=1737452950',
  },
  {
    id: 'brewdog-punk-ipa-remixed',
    name: 'BrewDog Punk IPA Remixed',
    style: 'IPA',
    abv: 5.8,
    brewingDays: 9,
    conditioningDays: 5,
    description: 'PINTER GOES PUNK. A bold and vibrant brew, bursting with hop-forward flavours and aromas. It pours a bright golden hue with a frothy, white head. On the nose, you\'ll be greeted with an enticing blend of citrus, pine, and tropical fruit notes. The taste is a crisp balance of hops and a subtle malt backbone, delivering layers of resinous pine, grapefruit, and a hint of pineapple.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/BrewDog-PunkIPARemixed_03copy_large_crop_center@2x.jpg?v=1729775842',
  },  
  {
    id: 'brewdog-hazy-jane-remixed',
    name: 'BrewDog Hazy Jane Remixed',
    style: 'Hazy IPA',
    abv: 6.0,
    brewingDays: 9,
    conditioningDays: 5,
    description: 'PINTER GOES HAZY. A luscious brew that envelops your senses in a cloud of tropical delight. This hazy, golden-orange ale pours with a fragrant bouquet of ripe mango, pineapple, and juicy passionfruit. The mouthfeel is incredibly smooth and silky, as waves of tropical fruit flavours wash over your palate. A subtle hop bitterness is present, but takes a backseat to the vibrant, juicy notes that dominate each sip.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/BrewDog-HazyJaneRemixed_03copy_large_crop_center@2x.jpg?v=1729685973',
  },
  {
    id: 'appalachian-mountain-brewery',
    name: 'Appalachian Mountain Brewery',
    style: 'Tropical IPA',
    abv: 6.5,
    brewingDays: 9,
    conditioningDays: 5,
    description: 'Introducing our Tropical IPA, a vibrant collaboration with Appalachian Mountain Brewery. Bursting with tropical flavours, this beauty features a blend of El Dorado, Mosaic, and Citra hops, complemented by refreshing pineapple and mango flavourings. With a bold finish and 6.5% ABV, it\'s the perfect balance of fruity sweetness and hoppy goodness.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Banner__AppalachianBrewery_large_crop_center@2x.png?v=1727452600',
  },
  {
    id: 'canary-pilsner',
    name: 'Canary Pilsner',
    style: 'German Pilsner',
    abv: 4.7,
    brewingDays: 10,
    conditioningDays: 10,
    description: '',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/CanaryPilsner_03_d9daf17d-fd0e-42e8-b923-8cf3d45cf895_large_crop_center@2x.jpg?v=1730908432',
  },
  {
    id: 'en-casa',
    name: 'En Casa',
    style: 'Mexican Lager',
    abv: 4.5,
    brewingDays: 10,
    conditioningDays: 10,
    description: 'Dry and light-bodied, low-level malt flavour. Delicately balanced with a subtle bitterness and crisp, clean aftertaste. Thirst-quenching and easy drinking. Pairs perfectly with a lime and a sunny day.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Banner_EnCasa_large_crop_center@2x.png?v=1715865222',
  },
  {
    id: 'space-hopper',
    name: 'Space Hopper',
    style: 'Double IPA',
    abv: 7.0,
    brewingDays: 7,
    conditioningDays: 7,
    description: 'Golden colour and a slight haze. Strong, intense hop flavour and aroma but with enough malt in the back to balance things out.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/SpaceHopper_03_large_crop_center@2x.jpg?v=1693557821',
  },
  {
    id: 'dark-matter',
    name: 'Dark Matter',
    style: 'Classic Stout',
    abv: 5.0,
    brewingDays: 5,
    conditioningDays: 7,
    description: 'A dark, sweet, full-bodied and slightly roasty ale. Roasted barley and malt aromas, and a hint of chocolate.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/DarkMatter_03_large_crop_center@2x.jpg?v=1693558249',
  },
  {
    id: 'sunlit',
    name: 'Sunlit',
    style: 'Lager',
    abv: 4.7,
    brewingDays: 10,
    conditioningDays: 15,
    description: 'The Ultimate Everyday Lager. This sunshine golden lager is crisp with lightly spicy Czech Saaz hops and balanced with smooth British malt. Lager inspired by everywhere, for everyone.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/SunlitLager_03_large_crop_center@2x.jpg?v=1737985872',
  },
  {
    id: 'public-house',
    name: 'Public House',
    style: 'IPA',
    abv: 4.2,
    brewingDays: 5,
    conditioningDays: 7,
    description: 'Malty & hoppy. A hop forward beer with a strong burst of piney, resinous and earthy characters. A seriously drinkable IPA.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/PublicHouse_Improved_03_large_crop_center@2x.jpg?v=1715850272',
  },
  {
    id: 'ancestors',
    name: 'Ancestor\'s',
    style: 'British Bitter',
    abv: 4.1,
    brewingDays: 8,
    conditioningDays: 5,
    description: '',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/HouseRangeShopImageBanner-01_large_crop_center@2x.png?v=1693487274',
  },
  {
    id: 'golden-grove',
    name: 'Golden Grove',
    style: 'Belgian Wit',
    abv: 4.6,
    brewingDays: 5,
    conditioningDays: 7,
    description: 'Belgian-style wheat beer that drinks light with a hazy appearance and delicate balance of citrus and spice flavours. Perfect for warm weather, it offers a lively, effervescent mouthfeel.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/GoldenGrove_03_1_large_crop_center@2x.jpg?v=1740045743',
  },
  {
    id: 'fourpure-citrus-ipa-remixed',
    name: 'Fourpure Citrus IPA Remixed',
    style: 'Citrus IPA',
    abv: 5.9,
    brewingDays: 8,
    conditioningDays: 6,
    description: 'Our remixed version of one of Fourpure\'s classic beers, the Citrus IPA immediately hits you with the iconic citrus bomb, tons of zest and juicy orange accompanied with piney hops and rich maltiness for a balanced finish.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/FourpureCitrusIPARemixed_03_copy_large_crop_center@2x.jpg?v=1734604766',
  },
  {
    id: 'sycamore-brewing',
    name: 'Sycamore Brewing',
    style: 'American Wheat',
    abv: 5.0,
    brewingDays: 8,
    conditioningDays: 5,
    description: 'Our American Wheat Beer, brewed in collaboration with Sycamore Brewing, offers a delightful balance of easy-drinking refreshment and subtle complexity. With a slight haze, it\'s approachable, light-bodied and perfect for laid-back gatherings and sunny days, it\'s the ultimate thirst-quencher.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/SycamoreAmericanWheat_Logo_04_large_crop_center@2x.jpg?v=1727452851',
  },
  {
    id: 'yeastie-boys-bigmouth-remixed',
    name: 'Yeastie Boys Bigmouth Remixed',
    style: 'Session IPA',
    abv: 4.7,
    brewingDays: 7,
    conditioningDays: 5,
    description: 'Pinter x Yeastie Boys. Inspired by the original, reimagined with the Pinter. A cover of a modern classic. Light and easy drinking golden ale bursting with juicy stone fruit, pineapple and the fragrant white grape aroma of New Zealand’s favourite hops, the mighty Nelson Sauvin.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Banner__YeastieBoysBigmouthRemixed_large_crop_center@2x.jpg?v=1749646995',
  },
  {
    id: 'razz-session',
    name: 'Razz Session',
    style: 'Sour Ale',
    abv: 4.5,
    brewingDays: 7,
    conditioningDays: 5,
    description: 'A LIVELY AND REFRESHING RASPBERRY-INFUSED SOUR BEER Perfect for laid-back gatherings and casual sipping. Bursting with the balanced tart and sweet notes of freshly-picked raspberries, it’s a sessionable brew that’s sure to spark joy with every sip.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/RazzSession_03_large_crop_center@2x.jpg?v=1726131182',
  },
  {
    id: 'inner-circle',
    name: 'Inner Circle',
    style: 'Pale Ale',
    abv: 4.0,
    brewingDays: 7,
    conditioningDays: 7,
    description: 'Our House Pale Ale is an easy-drinking, sessionable pale ale with subtle biscuit malt character and a harmonious blend of floral and orange zest notes. A delicate malt backbone provides a light sweetness, balanced by citrus hop notes and a gentle, piney bitterness.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/HouseRangeShopImageBanner-03_large_crop_center@2x.jpg?v=1696866177',
  },
  {
    id: 'stars-stripes',
    name: 'Stars & Stripes',
    style: 'American Pale Ale',
    abv: 4.5,
    brewingDays: 5,
    conditioningDays: 7,
    description: 'A touch of maltiness means it\'s super drinkable and well balanced. Solid hop aroma with a range of notes; citrus, floral, pine, resinous, spicy, tropical fruit. Pale golden to light amber colour and may show bready, toasty and biscuity hints of speciality malt character.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Stars_Stripes_03_large_crop_center@2x.jpg?v=1693558135',
  },
  {
    id: 'waltham-forest',
    name: 'Waltham Forest',
    style: 'Dark Fruit Cider',
    abv: 4.5,
    brewingDays: 8,
    conditioningDays: 3,
    description: 'The fresh dark fruit cider is a perfect combination of apples and blackcurrants with a strong aromatic flavour character, robust fresh and fruity flavour. It has beautiful hints of citrus that gives the fruit cider a refreshing and clean taste.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/WalthamForest_03_large_crop_center@2x.jpg?v=1693558916',
  },
  {
    id: 'whole-nine-yards',
    name: 'Whole Nine Yards',
    style: 'Cloudy Apple Cider',
    abv: 5.6,
    brewingDays: 8,
    conditioningDays: 3,
    description: 'Sweet, moreish and seductively tart. Bursting with more flavour than ever from apples. Perfectly refreshing year-round.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/WholeNineYards_03_large_crop_center@2x.jpg?v=1693558337',
  },
  {
    id: 'brewgooder-hazy-ipa-remixed',
    name: 'Brewgooder Hazy IPA Remixed',
    style: 'IPA',
    abv: 5.0,
    brewingDays: 7,
    conditioningDays: 5,
    description: 'A JUICY, HAZY, AND SUPER REFRESHING REMIX OF AN ORIGINAL. Packed with tropical pineapple and peach flavour. A hint of spicy resin from Centennial hops and a touch of fresh grapefruit citrus from Cascade hops. All at a crushable 5%.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Banner_HazyIPARemixed_large_crop_center@2x.jpg?v=1706112599',
  },
  {
    id: 'space-hopper-west-coast-edition',
    name: 'Space Hopper West Coast Edition',
    style: 'DDH IPA',
    abv: 7.0,
    brewingDays: 7,
    conditioningDays: 7,
    description: 'The second edition to the Space Hopper DIPA family. Dry, crisp and hoppy. Floral hops take centre stage providing a punchy, piney aroma. Background notes of peach, pineapple and orange bring a recognisable yet subtle fruitiness.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/SpaceHopperWestCoastEdition_03_large_crop_center@2x.jpg?v=1693556980',
  },
  {
    id: 'lemon-lime-hard-seltzer',
    name: 'Lemon & Lime Hard Seltzer',
    style: 'Hard Seltzer',
    abv: 4.7,
    brewingDays: 7,
    conditioningDays: 7,
    description: 'Our Lemon & Lime Seltzer offers a lively burst of bright lemon and tangy lime, balanced by a clean, effervescent finish. Light, bubbly, and with just the right amount of tartness, it’s a go-to choice for those who crave a refreshing beverage with a zesty twist.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/SeltzerSeries-Lemon_Lime_03_20a340ab-e472-474d-9a3b-9d76bd85d472_large_crop_center@2x.jpg?v=1722957024',
  },
  {
    id: 'shadow-cream',
    name: 'Shadow & Cream',
    style: 'Irish Cream Stout',
    abv: 5.4,
    brewingDays: 5,
    conditioningDays: 7,
    description: 'Strong roasted malt with dark chocolate and espresso flavours. Smooth, rich sweetness reminiscent of Irish Cream, with hints of vanilla and chocolate.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Shadow_Cream_03_large_crop_center@2x.jpg?v=1740480612',
  },
  {
    id: 'pear-with-me',
    name: 'Pear With Me',
    style: 'Perry Cider',
    abv: 6.0,
    brewingDays: 9,
    conditioningDays: 5,
    description: 'Notes of fresh ripe pears dominate, but not overwhelming, with a delicate tartness that cuts through the fruitiness. The cider’s body is light to medium, offering a gentle acidity that adds to a clean, dry finish.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Screenshot2025-07-16at12.03.29_large_crop_center@2x.png?v=1752666612',
  },
  {
    id: 'trooper-remixed',
    name: 'Trooper Remixed',
    style: 'British Beer',
    abv: 4.7,
    brewingDays: 7,
    conditioningDays: 5,
    description: 'Trooper, the iconic beer created by Iron Maiden, remixed with Pinter. Malt flavors and citric notes with a unique blend of hops give this deep golden ale a subtle hint of lemon. Includes collaboration glassware.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Banner__TrooperRemixedBundle-min_large_crop_center@2x.png?v=1747835665',
  },
  {
    id: 'prostmeister',
    name: 'Prostmeister',
    style: 'Oktoberfest Lager',
    abv: 6.5,
    brewingDays: 8,
    conditioningDays: 10,
    description: 'Crafted with precision and care, this Oktoberfest beer is a clean and crisp lager with delightful caramel and biscuit notes. It’s the perfect companion for festive gatherings, with a balanced bitterness and a touch of sweetness.',
    imageUrl: 'https://pinter.co.uk/cdn/shop/files/Prostmeister_03_large_crop_center@2x.jpg?v=1725007136',
  }  
];